default:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      database: im-xxxx-yyy
      schema: dbt_srangelp
      threads: 10
      timeout_seconds: 300
      priority: interactive
      keyfile: ${{ secrets.DBT_BIGQUERY_TOKEN }}
 
clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: "{{ env_var('CH_DB_HOST') }}"
      user: "{{ env_var('CH_DB_USER') }}"
      password: "{{ env_var('CH_DB_PASSWORD') }}"
      port: "{{ env_var('CH_DB_PORT', '9440') | as_number }}"
      schema: "{{ env_var('CH_DB_SCHEMA') }}"
      database: "{{ env_var('CH_DB_NAME') }}"
      secure: True
      send_receive_timeout: 1200
      threads: 10
