default:  
  outputs:
    agency_test:
      type: bigquery
      method: service-account
      database: "{{ env_var('BIGQUERY_DB_NAME') }}"
      schema: "{{ env_var('BIGQUERY_DB_SCHEMA') }}"
      threads: 10
      timeout_seconds: 300
      priority: interactive
      keyfile: conf/.dbt/gbq_creds.json
      
clickhouse:
  outputs:
    agency_test:
      type: clickhouse
      host: "{{ env_var('CH_DB_HOST') }}"
      user: "{{ env_var('CH_DB_USER') }}"
      password: "{{ env_var('CH_DB_PASSWORD') }}"
      port: "{{ env_var('CH_DB_PORT', '8443') | as_number }}"
      schema: "{{ env_var('CH_DB_SCHEMA') }}"
      database: "{{ env_var('CH_DB_NAME') }}"
      secure: True
      send_receive_timeout: 1200
      threads: 10