default:
  target: default
  outputs:
    default:
      type: bigquery
      method: service-account
      project: im-xxxx-yyy
      dataset: dbt_srangelp
      threads: 10
      timeout_seconds: 300
      priority: interactive
      keyfile: conf/.dbt/gbq_creds.json
      
clickhouse:
  target: option2
  outputs:
    option2:
      type: clickhouse
      host: "{{ env_var('CH_DB_HOST') }}"
      user: "{{ env_var('CH_DB_USER') }}"
      password: "{{ env_var('CH_DB_PASSWORD') }}"
      port: "{{ env_var('CH_DB_PORT', '8443') | as_number }}"
      schema: "{{ env_var('CH_DB_SCHEMA') }}"
      database: "{{ env_var('CH_DB_NAME') }}"
      secure: True
      send_receive_timeout: 1200
      threads: 10