name: dbt
on:
  schedule:
  # https://crontab.guru <-- for generating CRON expression
    - cron: '31 1 * * *'

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python enviroment
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dbt
        run: pip install dbt-core
      #- name: Install dependencies
        #run: dbt deps
      #- name: Run dbt
        #run: dbt run
      - name: Run dbt
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "dbt run "
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
          DBT_BIGQUERY_KEYFILE: ./DBT_BIQUERY_TOKEN.json
          DBT_PROFILES_DIR: ./conf/.dbt

