name: dbt
on:
  schedule:
  # https://crontab.guru <-- for generating CRON expression
    - cron: '00 21 * * *'
  workflow_dispatch:

jobs:
  dbt:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python enviroment
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install dbt
        run: pip3 install "dbt-bigquery >= 1.4.1" "Babel == 2.11.0" "Jinja2 == 3.1.2" "MarkupSafe == 2.1.2" "agate == 1.6.3" "attrs == 22.2.0" "betterproto == 1.2.5" "cachetools == 5.3.0" "certifi == 2022.12.7" "cffi == 1.15.1" "charset-normalizer == 3.0.1" "click == 8.1.3" "colorama == 0.4.6" "dbt-core == 1.4.1" "dbt-extractor == 0.4.1" "future == 0.18.3" "google-api-core == 2.10.2" "google-auth == 2.16.1" "google-cloud-bigquery == 3.5.0" "google-cloud-core == 2.3.2" "google-cloud-dataproc == 5.0.3" "google-cloud-storage == 2.7.0" "google-crc32c == 1.5.0" "google-resumable-media == 2.4.1" "googleapis-common-protos == 1.58.0" "grpcio == 1.51.3" "grpcio-status == 1.48.2" "grpclib == 0.4.3" "h2 == 4.1.0" "hologram == 0.0.15" "hpack == 4.0.0" "hyperframe == 6.0.1" "idna == 3.4" "isodate == 0.6.1" "jsonschema == 3.2.0" "leather == 0.3.4" "logbook == 1.5.3" "mashumaro == 3.3.1" "minimal-snowplow-tracker == 0.0.2" "msgpack == 1.0.4" "multidict == 6.0.4" "networkx == 2.8.8" "packaging == 21.3" "parsedatetime == 2.4" "pathspec == 0.10.3" "proto-plus == 1.22.2" "protobuf == 3.20.3" "pyasn1 == 0.4.8" "pyasn1-modules == 0.2.8" "pycparser == 2.21" "pyparsing == 3.0.9" "pyrsistent == 0.19.3" "python-dateutil == 2.8.2" "python-slugify == 8.0.0" "pytimeparse == 1.1.8" "pytz == 2022.7.1" "pyyaml == 6.0" "requests == 2.28.2" "rsa == 4.9" "six == 1.16.0" "sqlparse == 0.4.3" "stringcase == 1.2.0" "text-unidecode == 1.3" "typing-extensions == 4.5.0" "urllib3 == 1.26.14" "werkzeug == 2.2.3"
        #run: pip3 install dbt-bigquery
        #run: pip install "dbt-bigquery >= 1.4.1" "colorama == 0.4.6" "click == 8.1.3" "dbt-extractor == 0.4.1" "google-auth == 2.16.1" "cffi == 1.15.1" "packaging == 21.3" "parsedatetime == 2.4" "Babel == 2.11.0" "pycparser == 2.21" "pytimeparse == 1.1.8" "future == 0.18.3"
      - name: Install dependencies
        run: dbt deps
      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "DBT_BIGQUERY_TOKEN.json"
          json: ${{ secrets.DBT_BIGQUERY_TOKEN }}
          dir: './'
      - name: Run dbt
        run: dbt run
      #- name: Run dbt
        #uses: mwhitaker/dbt-action@master
        #with:
          #dbt_command: "dbt run "
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
          #DBT_BIGQUERY_KEYFILE: ./DBT_BIQUERY_TOKEN.json
          DBT_PROFILES_DIR: ./

