name: test

on:
  schedule:
   - cron:  '7 23 * * *'

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: dbt-run
        uses: mwhitaker/dbt-action@master
        with:
          dbt_command: "xdg-open /github/home/.dbt"
        env:
          DBT_BIGQUERY_TOKEN: ${{ secrets.DBT_BIGQUERY_TOKEN }}
